---
jobs:
- name: build
  serial: true
  public: true
  plan:
  - get: cf-cli-resource
    trigger: true
  - task: build
    privileged: true
    file: cf-cli-resource/ci/tasks/build-image.yml
  - put: resource-image-dev
    params:
      image: image/image.tar
    get_params:
      skip_download: true

- name: test-cf-cli-v6
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: cf-cli-resource
      passed: [build]
      trigger: true
    - get: resource-image-dev
      passed: [build]
      trigger: true
  - task: test
    image: resource-image-dev
    file: cf-cli-resource/ci/tasks/run-shellspec.yml
    vars:
      ccr-test-jobs: 4
      ccr-cf-cli-version: 6

- name: test-cf-cli-v7
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: cf-cli-resource
      passed: [build]
      trigger: true
    - get: resource-image-dev
      passed: [build]
      trigger: true
  - task: test
    image: resource-image-dev
    file: cf-cli-resource/ci/tasks/run-shellspec.yml
    vars:
      ccr-test-jobs: 4
      ccr-cf-cli-version: 7

resources:
- name: cf-cli-resource
  type: git
  icon: github
  source:
    uri: git@github.com:nulldriver/cf-cli-resource.git
    private_key: ((git_key.private_key))
    ignore_paths:
    - .devcontainer
    - .gitignore
    - .shellspec
    - CHANGELOG.md
    - LICENSE
    - NOTICE.md
    - README.md
    - examples
    - itest
    - pipeline-shellspec.yml
    - pipeline.yml

- name: resource-image-dev
  type: registry-image
  icon: docker
  source:
    repository: nulldriver/cf-cli-resource-dev
    tag: dev
    username: ((docker.username))
    password: ((docker.password))
