---
platform: linux

image_resource:
  type: registry-image
  source: {repository: aquasecurity/trivy}

inputs:
- name: cf-cli-resource

outputs:
- name: trivy-db

run:
  path: cf-cli-resource/tasks/extract-trivy-db
