---
platform: linux

image_resource:
  type: registry-image
  source: {repository: aquasec/trivy}

inputs:
- name: cf-cli-resource
- name: image
- name: trivy-db

params:
  IGNORE_POLICY_FILE:

run:
  path: cf-cli-resource/tasks/scan-image
