apiVersion: v1
kind: Service
metadata:
  name: overview-broker-service
spec:
  selector:
    app: overview-broker-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

